<a href="https://colab.research.google.com/github/JSJeong-me/winnereye/blob/main/dgul/8_keyword_ranking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#!pip install -r requirements.txt

In [2]:
!python -m pip install mysql-connector-python
!pip install PyMySQL==1.0.0
!pip install SQLAlchemy==1.4.17
!pip install cryptography
!pip install konlpy

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.7/dist-packages (8.0.28)
Requirement already satisfied: protobuf>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from mysql-connector-python) (3.17.3)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.7/dist-packages (from protobuf>=3.0.0->mysql-connector-python) (1.15.0)
Requirement already satisfied: PyMySQL==1.0.0 in /usr/local/lib/python3.7/dist-packages (1.0.0)
Requirement already satisfied: SQLAlchemy==1.4.17 in /usr/local/lib/python3.7/dist-packages (1.4.17)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from SQLAlchemy==1.4.17) (1.1.2)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from SQLAlchemy==1.4.17) (4.10.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->SQLAlchemy==1.4.17) (3.10.0.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->SQLAlchemy==1.4.17) (3.7.0)
Requirement already satisfied: cryptography in /usr/local/lib/python3.7/dist-packages (36.0.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography) (2.21)
Requirement already satisfied: konlpy in /usr/local/lib/python3.7/dist-packages (0.6.0)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.7/dist-packages (from konlpy) (1.19.5)
Requirement already satisfied: JPype1>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (1.3.0)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (4.2.6)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from JPype1>=0.7.0->konlpy) (3.10.0.2)

# Data Load

In [3]:
from datetime import datetime
from pytz import timezone

# 현재 시간을 가져온다.
now = datetime.now(timezone('Asia/Seoul'))
print(now)

candidate = '이재명'
portal = 'naver'
gen_date = '20220113'
No_Ranking = 5

# https://windybay.net/post/20/
date_time = now

2022-01-26 10:12:48.880177+09:00

In [4]:
import pymysql
from sqlalchemy import create_engine
import pandas.io.sql as pSql
import pandas as pd
import pickle


DATABASE = 'winnereye'

db = pymysql.connect(
  host='18.177.137.112', 
  port=3306, 
  user='winnereye', 
  passwd='Whd1347!1', 
  db=DATABASE, charset='utf8',autocommit=True)

In [5]:
sql = "SELECT rawdata from winnereye.dgul_{0}_{1}_{2};".format(candidate, portal, gen_date)

In [6]:
df = pd.read_sql_query(sql, db)

In [7]:
db.close()

In [8]:
df.head(5)

                                             rawdata
0                       양파같은 여자란말이지ㅎㅎㅎ 윤은 진짜 물건너갔네 축
1  배우자 리스크 내 개인적인 생각에는윤석열이 대선에 도전한건 김건희가 전부다 정권심판...
2                                         진짜 모습 궁금하네
3                       끼리끼리 만난다고 윤석열도 아니다 안철수밖에 없는듯
4                                왜그리감추냐기자한테 꼬리라도 친거냐

# 2.2 데이터 전처리

In [9]:
df.loc[1]['rawdata']  # 전처리 전

'배우자 리스크 내 개인적인 생각에는윤석열이 대선에 도전한건 김건희가 전부다 정권심판도 민생안정도 그 무엇도 아닌 내 여자하나 만족시키기 위함이다'

[전처리]

In [10]:
import re

def remove_white_space(text):
    text = re.sub(r'[\t\r\n\f\v]', ' ', str(text))
    return text

def remove_special_char(text):
    text = re.sub('[^ ㄱ-ㅣ가-힣 0-9]+', ' ', str(text))
    return text

df.rawdata = df.rawdata.apply(remove_white_space)
df.rawdata = df.rawdata.apply(remove_special_char)

In [11]:
df.loc[1]['rawdata']  # 전처리 후

'배우자 리스크 내 개인적인 생각에는윤석열이 대선에 도전한건 김건희가 전부다 정권심판도 민생안정도 그 무엇도 아닌 내 여자하나 만족시키기 위함이다'

# 2.3 토크나이징 및 변수 생성

[토크나이징]

In [12]:
from konlpy.tag import Okt

okt = Okt()

df['rawdata_token'] = df.rawdata.apply(okt.morphs)
#df['content_token'] = df.rawdata.apply(okt.nouns)

In [13]:
df['rawdata_token'].head(5)

0        [양파, 같은, 여, 자란말이지, ㅎㅎㅎ, 윤, 은, 진짜, 물, 건너갔네, 축]
1    [배우자, 리스크, 내, 개인, 적, 인, 생각, 에는, 윤석열, 이, 대선, 에,...
2                                       [진짜, 모습, 궁금하네]
3              [끼리끼리, 만난다고, 윤석열, 도, 아니다, 안철수, 밖에, 없는듯]
4                    [왜, 그리, 감추냐, 기자, 한테, 꼬리, 라도, 친거냐]
Name: rawdata_token, dtype: object

In [14]:
#df['content_token'].head(5)

###[한단어 제거]

[파생변수 생성]

In [15]:
df['token_final'] = df.rawdata_token #  + df.content_token

#df['count'] = df['count'].replace({',' : ''}, regex = True).apply(lambda x : int(x))

print(df.dtypes)

#df['label'] = df['count'].apply(lambda x: 'Yes' if x>=1000 else 'No')

rawdata          object
rawdata_token    object
token_final      object
dtype: object

In [16]:
df_drop = df['token_final'] # df[['token_final', 'label']]

In [17]:
df_drop.head()

0        [양파, 같은, 여, 자란말이지, ㅎㅎㅎ, 윤, 은, 진짜, 물, 건너갔네, 축]
1    [배우자, 리스크, 내, 개인, 적, 인, 생각, 에는, 윤석열, 이, 대선, 에,...
2                                       [진짜, 모습, 궁금하네]
3              [끼리끼리, 만난다고, 윤석열, 도, 아니다, 안철수, 밖에, 없는듯]
4                    [왜, 그리, 감추냐, 기자, 한테, 꼬리, 라도, 친거냐]
Name: token_final, dtype: object

[데이터 엑셀로 저장]

In [18]:
df_drop.to_csv('df_drop.csv', index = False, encoding = 'utf-8-sig')

# 2.4 단어 임베딩

[단어 임베딩]

In [19]:
# https://velog.io/@kiy7605/NLPL3WordEmbeddingKIY

from gensim.models import Word2Vec

embedding_model = Word2Vec(df_drop, \
                           sg = 1, # skip-gram
                           size = 100, \
                           window = 2, \
                           min_count = 1, \
                           workers = 4 \
                           )

print(embedding_model)

#model_result = embedding_model.wv.most_similar("윤석열")
#print(model_result)

Word2Vec(vocab=21806, size=100, alpha=0.025)


[임베딩 모델 저장 및 로드]

In [20]:
# https://velog.io/@kiy7605/NLPL3WordEmbeddingKIY


from gensim.models import KeyedVectors

embedding_model.wv.save_word2vec_format('petitions_tokens_w2v') # 모델 저장
loaded_model = KeyedVectors.load_word2vec_format('petitions_tokens_w2v') # 모델 로드

In [21]:
#model_result = loaded_model.most_similar("복어알")
#print(model_result)

# NEWS Keywords

In [22]:
#import pymysql
#from sqlalchemy import create_engine
#import pandas as pd
#import re

In [23]:
#DATABASE = 'winnereye'

In [24]:
# 연결

db = pymysql.connect(
  host='18.177.137.112', 
  port=3306, 
  user='winnereye', 
  passwd='Whd1347!1', 
  db=DATABASE, charset='utf8',autocommit=True)


candidate = '윤석열'
portal = 'naver'
gen_date = '20220101'

In [25]:
sql = "SELECT News_ID from winnereye.dgul_analysis_{0}_{1};".format(candidate, gen_date)
df = pd.read_sql_query(sql, db)

In [26]:
import re

def remove_white_space(text):
    text = re.sub(r'[\t\r\n\f\v]', ' ', str(text))
    return text

def remove_special_char(text):
    text = re.sub('[^ ㄱ-ㅣ가-힣]+', ' ', str(text))
    return text

In [27]:
list_keyword = df['News_ID'].str.split(' ', expand=False).sum()[:300]

In [28]:
def tokenizer(text):
    text = re.sub('[\[\]\(\)\"\']', '', str(text))
    text = text.split(', ')
    return text

In [29]:
list_keyword = tokenizer(list_keyword)

In [30]:
db.close()

In [ ]:
list_keyword

# WORD Ranking

In [32]:
text_list = str(list_keyword)

In [33]:
text_list

"['안철수', '“尹‧李', '양자토론,', '내', '두', '자릿수', '지지율', '무시하는', '행위”', '‘이재명', '의혹’', '제보자', '심장질환', '사망', '추정…CCTV에', '약', '봉투', '든', '모습', '3', '‘李', '변호사비', '대납’', '제보자', '사인', '심장질환', '추정…민주', '“간접살인·살인멸구?', '대가', '치를', '차례”', '사설', '탄도미사일', '제재', '나선', '美,', '“추가도발', '없을', '것”이라는', '文정권', '사설', '“90년생부터', '한푼도', '못', '받는다”는데,', '연금', '개혁', '모르쇠하나', '현장에선', '개인투자자', '울리는', '물적분할', '‘4자', '대결’', '尹', '38.8%', 'VS', '李', '32.8%', 'VS', '安', '12.1%', '코리아리서치', '오병상의', '코멘터리', '심상정', '위기,', '진보정치의', '3중고', '안철수,', '윤석열', '유튜브', '언급하며', '며칠', '내로', '구독자', '앞설', '것', '나이트포커스', '위기의', '정의당,', '열', '받은', '국민의당', '이재명·윤석열만', 'TV토론?…안철수·심상정', '측', '불만', '제기', '“이재명,', '연쇄', '간접살인”', '국민의힘', '‘제보자', '사망’', '맹공', '윤석열', '“4월', '전기요금', '인상,', '전면', '백지화”…', '文정부', '‘탈원전', '때리기’', '미리보는', '이데일리', '신문기업소송', '칼', '쥐는', '수탁위…전문성·독립성', '도마에', '41', '다자대결', '엇갈린', '결과…李', '37%', '尹', '28%,', '尹', '38.8%', '李', '32.8%종합', '이재명·윤석열', '양자', '토론에…정의·국민의당', '거센', '반발종합2보', '김동연', '부총리', '시절', '靑', '정책실장', '등과', '고성...李·尹', '경제', '철학', '없다', '안철수', '180석', '민주당,', '잘하나?…', '미니정당', '지적', '적극', '반박', '이재명', '역대', '민주정부', '과도하게', '억제...\\\\용적률', '500%', '재건축', '공약', '‘이재명', '변호사비', '대납', '의혹', '제보자’', '사인', '심장질환', '추정', '51', '이재명', '용적률', '500%', '4종', '주거지', '신설', 'vs', '윤석열', '전기요금', '인상', '백지화', '이재명-윤석열,', '설', '연휴', '전', '양자', 'TV토론...안철수', '기득권', '담합', '56', '안철수', '\\\\병사', '월급', '200만원', '공약은', '매표', '행위···포퓰리즘은', '망국병', '59', '60', '61', '62', '사인은', '심장질환...與', '사과', '촉구', 'vs', '野', '의문', '여전', '김정화,', '박영선', '직격', '“김건희에', '아전인수', '해석…‘생태탕’스럽다”', '尹', '38.8%-李', '32.8%-安', '12.1%…野', '단일', '후보,', '尹', '42.1%', 'vs', '安', '39.8%', '70', '안철수', '단일화,', '양당이', '어떻게든', '저를', '없애려는', '술수종합', '안철수', '“국민통합내각', '꾸려', '좌우', '가리지', '않고', '전문가', '기용”', '이재명', '변호사비', '대납', '의혹', '제보자', '부검', '결과', '“심장질환에', '의한', '사망”', '백운기의', '뉴스와이드', '김건희', '씨', '7시간', '통화', '공개', '예고', '논란', '/', '안철수', '이재명-윤석열만', '토론?', '3자로', '하자', '86', '김혜경,', '대구', '동화사', '방문…사찰', '찾아', '불교계와', '소통', '행보', '‘이재명', '의혹’', '제보자', '심장질환', '사망', '추정…CCTV에', '약', '봉투', '든', '모습', '안동시', '관권', '선거', '논란', '휩싸여...이재명', '지지선언', '보도자료', '배포', '90', '변호사비', '대납', '의혹', '제보자', '1차부검', '결과', '심장', '질환', '추정', '‘이재명', '변호사비']"

In [34]:
from collections import Counter

words = re.findall('\w+',text_list)
ranking = Counter(words).most_common(10)

new_ranking = []
for x, i in ranking:
  if len(x) > 1:
    #print(x, i)
    new_ranking.append(x)

print('Key words: {0}'.format(new_ranking))

Key words: ['이재명', '안철수', '제보자', '의혹', '심장질환', '추정', '변호사비']

In [35]:
#new_ranking

In [36]:
counter = 0

while counter < len(new_ranking):
  try:
    for i in new_ranking:
      loaded_model.wv[i]
      #print("OK")
  except  KeyError:    # 예외가 발생했을 때 실행됨
    new_ranking.remove(i)
    #print('예외가 발생했습니다.')
  finally:
    counter += 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).

In [37]:
len(new_ranking)

6

In [38]:
keywords =[]
news_embedding = pd.DataFrame(keywords, 
                              columns = new_ranking,
                              index= ['Ranking1', 'Ranking2', 'Ranking3', 'Ranking4', 'Ranking5'])

In [39]:
counter = 0
for i in new_ranking:
  #print(i+'\t : ')
  model_result = loaded_model.most_similar(i, topn=No_Ranking)
  for j in range(No_Ranking):
    p, q = model_result[j]
    news_embedding.iloc[j][i] = p
  #print(model_result)

In [40]:
news_embedding

          이재명  안철수 제보자  의혹  심장질환   추정
Ranking1   형수   대통  부부  사건  여론몰이  막을까
Ranking2   죄명  홍준표  기사  조국    추정   타격
Ranking3   욕설   이번  줄리  살인    정경   털어
Ranking4   쌍욕   선거  검사  여당   막을까   정경
Ranking5  대장동    뒤  뉴스  자질    방향   게임

### To save rangking data into Database: ranking_{후보자}_{Portal}_{News_Date}

In [41]:
import mysql.connector

mydb = mysql.connector.connect(
  host="18.177.137.112",
  user="winnereye",
  password="Whd1347!1",
  database="winnereye"
)

In [42]:
mycursor = mydb.cursor()

In [43]:
mycursor.execute("use winnereye")
mycursor = mydb.cursor()
table_name = 'ranking_{0}_{1}_{2}'.format(candidate, portal, gen_date)

In [44]:
table_columns = news_embedding.columns.tolist()

In [45]:
table_columns

['이재명', '안철수', '제보자', '의혹', '심장질환', '추정']

In [46]:
number_of_columns = len(table_columns)

In [47]:
number_of_columns

6

In [48]:
string_col = []
for i in table_columns:
  #print(i)
  string_col.append('{0} varchar(100)'.format(i))

In [49]:
#string_col

In [50]:
def tokenizer(text):
    text = re.sub('[\[\]\']', '', str(text))
    return text

In [51]:
string_new = tokenizer(string_col)

In [52]:
string_new

'이재명 varchar(100), 안철수 varchar(100), 제보자 varchar(100), 의혹 varchar(100), 심장질환 varchar(100), 추정 varchar(100)'

In [53]:
table_name

'ranking_이재명_naver_20220113'

In [54]:
mycursor.execute("CREATE TABLE {1} ( {0} ) DEFAULT CHARACTER SET utf8 COLLATE UTF8_GENERAL_CI".format(string_new, table_name) )

In [55]:
mycursor.close()

True

### Data Load

In [56]:
news_embedding

          이재명  안철수 제보자  의혹  심장질환   추정
Ranking1   형수   대통  부부  사건  여론몰이  막을까
Ranking2   죄명  홍준표  기사  조국    추정   타격
Ranking3   욕설   이번  줄리  살인    정경   털어
Ranking4   쌍욕   선거  검사  여당   막을까   정경
Ranking5  대장동    뒤  뉴스  자질    방향   게임

In [57]:
# 연결
db_url = 'mysql+pymysql://winnereye:Whd1347!1@18.177.137.112/winnereye'
# 엔진생성(절차)
engine = create_engine( db_url, encoding='utf8' )
# 실연결
conn = engine.connect()

# Table Name
#table_name = table_name
#print(table_name)
news_embedding.to_sql(name=table_name, con=engine, if_exists='replace', index = False)
# 해제
conn.close()